Added TextBox control and sample
fabulous-dev/Fabulous.Avalonia pull request #16
Opened 2022-12-04 05:47 UTC by ConradRoesch

2022-12-05 10:55 UTC, edgarfgp requested changes
Awesome. Thanks for this :). I just added couple of comments

2022-12-05 10:55 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/TextBox.fs
> +
Can we also add a wrapper for: 
- UndoLimit
- SelectionStart
- SelectionEnd

2022-12-05 10:55 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/TextBox.fs
> +
Can we also add event wrappers for :
- CopyingToClipboardEvent
- PastingFromClipboardEvent

You can use **Attributes.defineEvent**
ie:
```fsharp
let CopyingToClipboardEvent =
        Attributes.defineEvent<RoutedEventArgs> "TextBox_CopyingToClipboardEvent" (fun target ->
            (target :?> TextBox).CopyingToClipboard)
```

2022-12-06 11:20 UTC, ConradRoesch commented
Thank you for the feedback and code formatting tips. I should be be able to get to those missing wrappers shortly. Are there any particular controls or other developments that you could use some help with in the near term?

2022-12-06 11:33 UTC, edgarfgp commented
> Thank you for the feedback and code formatting tips. I should be able to get to those missing wrappers shortly. Are there any particular controls or other developments that you could use some help with in the near term?

I'm creating a list of controls to help us with the missing ones. I will create an issue to track this later today :)

2022-12-07 21:31 UTC, edgarfgp commented
I’m merging this as it is and work on the playground app to help us with the testing . For now you can testing it using the counter app but not commit the changes 😀

2022-12-07 21:32 UTC, edgarfgp approved these changes

2022-12-07 21:34 UTC, merged