Add NumericUpDown control
fabulous-dev/Fabulous.Avalonia pull request #33
Opened 2022-12-12 05:04 UTC by ConradRoesch

Note that the Value property is of type Nullable<decimal>, since the underlying Avalonia control was recently reworked to treat an empty entry as null (https://github.com/AvaloniaUI/Avalonia/pull/8259). 

In a Fabulous context, is a nullable Value property the desired behavior for this control? Unlike the Date and Time picker controls, a non-nullable value for NumericUpDown cannot be enforced solely by the constructor, since the user has the option to manually clear the input via keyboard entry. (Note also that watermark visibility is contingent on the Value property being nullable.)

2022-12-12 17:12 UTC, edgarfgp requested changes
Thanks for this 👍.  Just couple comments

2022-12-12 17:12 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
> +    let ValueChanged =
See my previous comment. For this one, we can use `Attributes.defineAvaloniaPropertyWithChangedEvent` with converters to massage the value :) 
```fsharp
let ValueChanged =
        Attributes.defineAvaloniaPropertyWithChangedEvent
            "NumericUpDown_ValueChanged"
            NumericUpDown.ValueProperty
            Option.toNullable
            Option.ofNullable
```

2022-12-12 17:12 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
> +    let LostFocus =
I believe this one should not be here. This is part of the Interactive. fs Pending TODO. 

As NumericUpDown inherits <- TemplatedControl <- Control <- InputElement <- `Interactive`. We should be able to access to the events there

2022-12-12 17:12 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
> +        static member inline NumericUpDown<'msg>(value: Nullable<decimal>, valueChanged: Nullable<decimal> -> 'msg) =
See my previous comments. This now can we a `decimal option` and be more F# friendly :) 

```fsharp
static member inline NumericUpDown<'msg>(value: decimal option, valueChanged: decimal option -> 'msg) =
            WidgetBuilder<'msg, IFabNumericUpDown>(
                NumericUpDown.WidgetKey,
                NumericUpDown.Value.WithValue(value),
                NumericUpDown.ValueChanged.WithValue(ValueEventData.create value (fun args -> valueChanged args |> box))
            )
```

2022-12-12 17:12 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
> +            value: System.Globalization.NumberFormatInfo
We could `open System.Globalization` at the top if possible

2022-12-12 17:12 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
> +            value: System.Globalization.NumberStyles
We could `open System.Globalization` at the top if possible

2022-12-12 17:12 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
> +            value: Avalonia.Data.Converters.IValueConverter
We could `open Avalonia.Data.Converters` at the top if possible

2022-12-12 20:57 UTC, ConradRoesch commented on src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
> +    let Value =
Thank you for providing the converter code along with the explanation (my background is C#, so I'm still learning many of the features baked into F#). I'm sure I'll see this converter again as we work through the remaining controls!

2022-12-13 08:59 UTC, edgarfgp commented on src/Fabulous.Avalonia/Widgets/Controls/NumericUpDown.fs
> +    let Value =
No worries,  happy to help :). Tim did the same for me a year ago when I started with F# and Fabulous.

2022-12-14 05:27 UTC, edgarfgp approved these changes

2022-12-14 05:28 UTC, edgarfgp commented
Awesome 👍 . Thanks

2022-12-14 05:28 UTC, merged